[package]
name = "vexide-simulator-protocol"
description = "JSON-based protocol enabling communication between VEX robot simulators and user-facing frontends"
version = "0.2.0"
edition = "2021"
homepage = "https://vexide.dev"
repository = "https://github.com/vexide/simulator-protocol"
license = "MIT"

[dependencies]
base64 = { version = "0.22.1" }
mint = { version = "0.5.9", features = ["serde"] }
rgb = { version = "0.8.45", features = ["serde"] }
serde = { version = "1.0.201", default_features = false, features = [
    "derive",
    "alloc",
] }
